name: Update TODO List

on:
  push:
    branches:
      - main

jobs:
  update_todo_list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read TODO.txt file
        id: read_todo
        run: |
          echo "::set-output name=todo::$(cat TODO.txt)"

      - name: Add TODO items to project
        uses: JasonEtco/todoist-sync@v2
        with:
          token: ${{ secrets.TODOIST_API_TOKEN }}
          content: ${{ steps.read_todo.outputs.todo }}
